#define SUCCESSFULL_EXIT 0
#define ILLEGAL_ARG_EXIT 1
#define INVALID_STR2INT_ARRAY_EXIT 2
#define FORK_ERROR_EXIT 3
#define FIFO_ERROR_EXIT 4
#define READING_FIFO_ERROR 5

#define SERVER_FIFO "/tmp/requests"
